import { CommandKind, ItemCategory } from "../types";
import type { ItemDef } from "./item-def";

/**
 * The frozen item pool. Hand-curated data — the dev-time generator (post-MVP)
 * emits entries in this shape.
 */
export const ITEM_DEFS: ItemDef[] = [
  {
    id: "basic-thruster",
    name: "Basic Thruster",
    category: ItemCategory.Thruster,
    subcategory: "brawler",
    mass: 5,
    maxHealth: 10,
    powerDraw: 1,
    price: 30,
    stats: {
      thrust: 1,
      maxTurnRate: 0.7, // rad/s — capital ships turn like capital ships
      trailLength: 20,
      trailWidth: 5,
      trailColor: "128, 216, 255",
    },
  },
  {
    id: "basic-weapon",
    name: "Autocannon",
    category: ItemCategory.Weapon,
    subcategory: "gun",
    mass: 5,
    maxHealth: 10,
    powerDraw: 1,
    price: 45,
    stats: {
      damage: 5,
      cooldown: 0.9,
      projectileSpeed: 650,
      lifetime: 2.2,
      arc: 110,
      burst: 1,
      burstInterval: 0,
    },
  },
  {
    id: "burst-blaster",
    name: "Burst Blaster",
    category: ItemCategory.Weapon,
    subcategory: "burst",
    mass: 7,
    maxHealth: 10,
    powerDraw: 2,
    price: 75,
    stats: {
      damage: 8,
      cooldown: 3.2,
      projectileSpeed: 600,
      lifetime: 2,
      arc: 130,
      burst: 3,
      burstInterval: 0.18,
    },
  },
  {
    id: "static-reactor",
    name: "Static Reactor",
    category: ItemCategory.Reactor,
    subcategory: "fission",
    mass: 12,
    maxHealth: 15,
    powerDraw: 0,
    price: 55,
    stats: {
      output: 13,
      allowReroute: false,
    },
  },
  {
    id: "relay-reactor",
    name: "Relay Reactor",
    category: ItemCategory.Reactor,
    subcategory: "fission",
    mass: 14,
    maxHealth: 14,
    powerDraw: 0,
    price: 100,
    stats: {
      output: 15,
      allowReroute: true,
    },
  },
  {
    id: "basic-cockpit",
    name: "Standard Cockpit",
    category: ItemCategory.Command,
    subcategory: "cockpit",
    mass: 6,
    maxHealth: 12,
    powerDraw: 1,
    price: 40,
    stats: {
      kind: CommandKind.Cockpit,
      manualFire: true,
      navPoints: 0,
      weaponBonus: 1,
      shieldBonus: 1,
      engineBonus: 1,
    },
  },
  {
    id: "gunner-cockpit",
    name: "Gunner Cockpit",
    category: ItemCategory.Command,
    subcategory: "cockpit",
    mass: 7,
    maxHealth: 12,
    powerDraw: 1,
    price: 70,
    stats: {
      kind: CommandKind.Cockpit,
      manualFire: true,
      navPoints: 0,
      weaponBonus: 1.2,
      shieldBonus: 0.85,
      engineBonus: 1,
    },
  },
  {
    id: "field-bridge",
    name: "Field Bridge",
    category: ItemCategory.Command,
    subcategory: "bridge",
    mass: 10,
    maxHealth: 14,
    powerDraw: 2,
    price: 95,
    stats: {
      kind: CommandKind.Bridge,
      manualFire: false,
      navPoints: 3,
      weaponBonus: 1.1,
      shieldBonus: 1.25,
      engineBonus: 1,
    },
  },
  {
    id: "tactical-bridge",
    name: "Tactical Bridge",
    category: ItemCategory.Command,
    subcategory: "bridge",
    mass: 11,
    maxHealth: 14,
    powerDraw: 2,
    price: 115,
    stats: {
      kind: CommandKind.Bridge,
      manualFire: true,
      navPoints: 6,
      weaponBonus: 1,
      shieldBonus: 1.1,
      engineBonus: 1.05,
    },
  },
  {
    id: "stable-drive",
    name: "Stable Jump Drive",
    category: ItemCategory.Drive,
    subcategory: "stable",
    mass: 10,
    maxHealth: 12,
    powerDraw: 1,
    price: 85,
    stats: {
      chargeTime: 20,
      chargeInCombat: true,
    },
  },
  {
    id: "basic-shield",
    name: "Bubble Shield",
    category: ItemCategory.Shield,
    subcategory: "bubble",
    mass: 8,
    maxHealth: 12,
    powerDraw: 1,
    price: 65,
    stats: {
      capacity: 45,
      chargeRate: 7,
      chargeDelay: 2.5,
    },
  },
];
